# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Ban\PycharmProjects\bantest\first.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 582)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.comboBox = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 290, 74, 22))
        self.comboBox.setObjectName("comboBox")
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(720, 320, 61, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.personal = QtWidgets.QListWidget(self.centralWidget)
        self.personal.setGeometry(QtCore.QRect(10, 40, 171, 241))
        self.personal.setObjectName("personal")
        self.personDButton = QtWidgets.QPushButton(self.centralWidget)
        self.personDButton.setGeometry(QtCore.QRect(100, 10, 77, 25))
        self.personDButton.setObjectName("personDButton")
        self.addSubtitleText = QtWidgets.QLineEdit(self.centralWidget)
        self.addSubtitleText.setGeometry(QtCore.QRect(100, 290, 531, 20))
        self.addSubtitleText.setObjectName("addSubtitleText")
        self.listWidget = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget.setGeometry(QtCore.QRect(190, 10, 601, 271))
        self.listWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 320, 451, 27))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.playButton.setDefault(False)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout.addWidget(self.playButton)
        self.horizontalSlider = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.horizontalSlider.setMaximum(999)
        self.horizontalSlider.setProperty("value", 0)
        self.horizontalSlider.setSliderPosition(0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.personIButton = QtWidgets.QPushButton(self.centralWidget)
        self.personIButton.setGeometry(QtCore.QRect(10, 10, 77, 25))
        self.personIButton.setObjectName("personIButton")
        self.submit = QtWidgets.QPushButton(self.centralWidget)
        self.submit.setGeometry(QtCore.QRect(640, 290, 71, 20))
        self.submit.setObjectName("submit")
        self.timeShow = QtWidgets.QLabel(self.centralWidget)
        self.timeShow.setGeometry(QtCore.QRect(480, 319, 71, 25))
        self.timeShow.setObjectName("timeShow")
        self.timeIButton = QtWidgets.QPushButton(self.centralWidget)
        self.timeIButton.setGeometry(QtCore.QRect(631, 320, 75, 23))
        self.timeIButton.setObjectName("timeIButton")
        self.timeDButton = QtWidgets.QPushButton(self.centralWidget)
        self.timeDButton.setGeometry(QtCore.QRect(550, 320, 75, 23))
        self.timeDButton.setObjectName("timeDButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 350, 761, 181))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.Save = QtWidgets.QPushButton(self.centralWidget)
        self.Save.setGeometry(QtCore.QRect(700, 540, 71, 20))
        self.Save.setObjectName("Save")
        self.insertBtn = QtWidgets.QPushButton(self.centralWidget)
        self.insertBtn.setEnabled(False)
        self.insertBtn.setGeometry(QtCore.QRect(710, 290, 71, 20))
        self.insertBtn.setObjectName("insertBtn")
        self.setBtn = QtWidgets.QPushButton(self.centralWidget)
        self.setBtn.setGeometry(QtCore.QRect(620, 540, 71, 20))
        self.setBtn.setObjectName("setBtn")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 797, 17))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionOpen_Subtitle = QtWidgets.QAction(MainWindow)
        self.actionOpen_Subtitle.setObjectName("actionOpen_Subtitle")
        self.menu.addAction(self.action)
        self.menu.addAction(self.actionOpen_Subtitle)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setText(_translate("MainWindow", "0.5"))
        self.personDButton.setText(_translate("MainWindow", "-"))
        self.playButton.setText(_translate("MainWindow", "Play"))
        self.personIButton.setText(_translate("MainWindow", "+"))
        self.submit.setText(_translate("MainWindow", "Submit"))
        self.timeShow.setText(_translate("MainWindow", "00:00/00:00"))
        self.timeIButton.setText(_translate("MainWindow", "+"))
        self.timeDButton.setText(_translate("MainWindow", "-"))
        self.Save.setText(_translate("MainWindow", "Save"))
        self.insertBtn.setText(_translate("MainWindow", "Insert"))
        self.setBtn.setText(_translate("MainWindow", "Set"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.action.setText(_translate("MainWindow", "Open MP3"))
        self.actionOpen_Subtitle.setText(_translate("MainWindow", "Open Subtitle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

